[build]
  publish = "website"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/features"
  to = "/features.html"
  status = 200

[[redirects]]
  from = "/commands"
  to = "/commands.html"
  status = 200

[[redirects]]
  from = "/support"
  to = "/support.html"
  status = 200
